### ISSUE TITLE
Setting of the Scene Design and Editing Experiments.

### ISSUE THREAD

**Issue by Hai-chao-Zhang** [KovenYu/uORF#3]
Hi, thanks for your great work.
I'm trying to reproduce your scene editing baseline. I'm wondering how to get the object moving results in the paper? It's performed by editing slot features before sending them to the decoder or directly manipulating the NeRF volume before the composition.

**Comment by KovenYu** [comment]
Hi, thanks for asking!

Since we represent objects in camera frame instead of recovering pose under a canonical frame, we do the latter -- to move an object we actually move the coordinates (corresponding to the target object slot) in the opposite direction.

It is related to this line of code:
https://github.com/KovenYu/uORF/blob/cc3ab8990a8d0839dae80da7dd75f665f721d83b/models/uorf_manip_model.py#L203
