### ISSUE TITLE
Lambda Perceptual

### ISSUE THREAD

**Issue by alextrevithick** [KovenYu/uORF#4]
Hi,

I am wondering about why the weight for the perceptual loss is only 0.006. What happens when it is higher?

Thanks!

**Comment by KovenYu** [comment]
Hi,

Thanks for your interest! I actually did not explore that. The value was empirically set and had never been tuned. They have different gradient magnitude so it should not be simply set to 1. My intuition is that a higher weight should yield similar results, because perc loss is only used for improving quality (alleviating uncertainty issue of L2 loss). Feel free to try different values by yourself!

**Comment by alextrevithick** [comment]
Thanks for your quick response. I was surprised by the great gains in lpips from this simple loss addition, and am now trying it in my own project.

Thanks for your good work!
