### ISSUE TITLE
Question about segmentation and manipulation

### ISSUE THREAD

**Issue by KelestZ** [KovenYu/uORF#7]
Hi, thanks for the efforts and the work is interesting. I have two questions here:
1) Is it the right way to predict segmentations using argmax(integrate(weight * density), slot_dim)? Seems that it could be wrong when occlusion occurs. I am showing a rendered example (the segm on top and the image on bottom) as below. I'm referring to the two cylinders on the right.

![00000_sc0000_az00_render_mask3](https://user-images.githubusercontent.com/27111467/150461000-d17cdc09-91e6-4f32-8bba-e8b225cb47d8.png)
![00000_sc0000_az00_x_rec3](https://user-images.githubusercontent.com/27111467/150461038-08ca7879-62f6-4acd-8311-e9c3397fabed.png)

2) How can I manipulate clever scenes?
>> FileNotFoundError: [Errno 2] No such file or directory: './clevr_567_test/00000_sc0000_az00_moved.png'

 I'm having this question because a background slot view contains object shadows as shown below. So how will these shadows be during manipulations?

![image](https://user-images.githubusercontent.com/27111467/150468021-05418099-e0f3-4171-9d98-82a2607bd9cb.png)

**Comment by KelestZ** [comment]
Aside, you might put a wrong input image in Fig.1 where the yellow and the blue chair have a different orientation from the reconstructed ones.

![image](https://user-images.githubusercontent.com/27111467/150471097-e6680129-0cdf-4c37-808d-897f5b2acbc7.png)

**Comment by KovenYu** [comment]
Hi Peiye,

Thanks for your question! 

1. Yeah, I also feel that is not the best way to do it. Perhaps accumulative transmittance might be a better measure? I did not get a chance to test this. Would be happy to learn from you!

2. The error msg appears because in my evaluation code I assumed (1) there are GT images to compute some quantitative metrics, and (2) you have the mask of the object-to-move. But both assumptions are not necessary to do manipulation (they are just for evaluation), so you can remove corresponding codes.

The shadow is not intrinsic to background. The shadow appears because I visualize the "masked" background, so objects can cast shadows. Hence, if you move an object, most of its shadow will follow it (but maybe the soft shadow would not).

3. Thank you for the note about Figure 1! It is actually due to imperfect inference, that is, inference on the yellow chair's pose is not correct. But I think that is understandable, because visually it is not very easy to tell both poses at a glance (which is why I did not notice LOL).
